#### Single Value Decomposition
- Example 1

In [2]:
import numpy as np
from scipy.linalg import svd
# define a matrix
A = np.array([[1,1,0], [0,0,1]])
print(A)
U, s, VT = svd(A)
print("----------------------------")
print(U) # U matrix
print("----------------------------")
print(s) # summation matrix 
print("----------------------------")
print(VT) # Vtranspose

[[1 1 0]
 [0 0 1]]
----------------------------
[[1. 0.]
 [0. 1.]]
----------------------------
[1.41421356 1.        ]
----------------------------
[[ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]
 [ 0.70710678 -0.70710678  0.        ]]


- Example 2

In [ ]:
import numpy as np
from scipy.linalg import svd
# define a matrix
A = np.array([[1,1],[1,0],[0,1]])
print(A)
U, s, VT = svd(A)
print("----------------------------")
print(U) # U matrix
print("----------------------------")
print(s) # summation matrix 
print("----------------------------")
print(VT) # Vtranspose

### Pseudo Inverse of a Matrix
- Moore-Penrose inverse

In [2]:
A = np.array([[1, 1,0], [0, 0, 1]])
#A = np.array([[7, 2], [3, 4], [5, 3]])
# D - Singular Value 
# V - Sqrt of eigen val of AA^T
U, D, V = np.linalg.svd(A)
# rows n columns A.shape
# D_plus is A^T with zeros filled in it
D_plus = np.zeros((A.shape[0], A.shape[1])).T 

D_plus[:D.shape[0], :D.shape[0]] = np.linalg.inv(np.diag(D)) # Epsion+
A_plus = V.T.dot(D_plus).dot(U.T)# A+
A_plus
print(A_plus)

[[0.5 0. ]
 [0.5 0. ]
 [0.  1. ]]


In [3]:
# A = np.array([[1, 1,0], [0, 0, 1]])
A = np.array([[7, 2], [3, 4], [5, 3]])
# D - Singular Value 
# V - Sqrt of eigen val of AA^T
U, D, V = np.linalg.svd(A)
# rows n columns A.shape
# D_plus is A^T with zeros filled in it
D_plus = np.zeros((A.shape[0], A.shape[1])).T 

D_plus[:D.shape[0], :D.shape[0]] = np.linalg.inv(np.diag(D)) # Epsion+
A_plus = V.T.dot(D_plus).dot(U.T)# A+
A_plus
print(A_plus)

[[ 0.16666667 -0.10606061  0.03030303]
 [-0.16666667  0.28787879  0.06060606]]
