# Lab 2

- Code 1

In [2]:
import numpy as np

In [3]:
# concatenating in row form
A = np.array([1,2,7,4,1,8,3,5])# vector
A1 = np.array( range(6))
Abig = np.concatenate( (A,A1) )
print(Abig)

[1 2 7 4 1 8 3 5 0 1 2 3 4 5]


- Code 2

In [4]:
# concatenating in column form
import numpy as np
A = np.array([[10,1,1],[1,10,1],[1,1,10]])# vector
A1 = np.array( [[12,12,12]]).T
Abig=np.column_stack((A, A1))
print(Abig)

[[10  1  1 12]
 [ 1 10  1 12]
 [ 1  1 10 12]]


- Code 3

In [ ]:
from sympy import *

In [ ]:
# Gauss-Jordan Method
# Reduced Row Echelon Form (given in notes) here the leading element is always "1"
M=Matrix([[10,1,1,12],[1,10,1,12],[1,1,10,12]])
M_rref = M.rref()
print(M_rref)
# (0, 1, 2) (the column index of leading element)
# columns having only one non-zero element
#   0  1  2  3
# [[1, 0, 0, 1],
# [0, 1, 0, 1],
# [0, 0, 1, 1]]

- Code 4

In [ ]:
from scipy.linalg import lu

In [ ]:
# LU decomposition
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
p, l, u = lu(A)
# p - permutation matrix
# l - lower triangular matrix
# u - upper triangular matrix
print(p)
print(l)
print(u)

- Code 5

In [4]:
# solving linear equation using LU decomposition
from scipy.linalg import lu_factor, lu_solve
A = np.array([[10,1,1],[1,10,1],[1,1,10]])
b = np.array([12, 12, 12])
lu, piv = lu_factor(A)
x = lu_solve((lu, piv), b)
print(x)

[1. 1. 1.]


- Code 6

In [5]:
# choklesky decomposition - matrix with +ve definite or |A| > 0 
A = np.array([[6, 3, 4, 8], [3, 6, 5, 1], [4, 5, 10, 7], [8, 1, 7, 25]])
L = np.linalg.cholesky(A)
print(L)
final = np.dot(L,L.T) # A = L*L^T 
print(final) # getting back the yield

[[ 2.44948974  0.          0.          0.        ]
 [ 1.22474487  2.12132034  0.          0.        ]
 [ 1.63299316  1.41421356  2.30940108  0.        ]
 [ 3.26598632 -1.41421356  1.58771324  3.13249102]]
[[ 6.  3.  4.  8.]
 [ 3.  6.  5.  1.]
 [ 4.  5. 10.  7.]
 [ 8.  1.  7. 25.]]


- Code 7

In [7]:
import pprint # align the output in matrix form rather than printing it into a straight line
import scipy
import scipy.linalg # SciPy Linear Algebra Library
A = np.array([[6, 3, 4, 8], [3, 6, 5, 1], [4, 5, 10, 7], [8, 1, 7, 25]])
L = scipy.linalg.cholesky(A, lower=True)
U = scipy.linalg.cholesky(A, lower=False)

pprint.pprint(A) # original matrix
pprint.pprint(L) # lower triangular matrix
pprint.pprint(U) # lower triangular matrix's transpose

array([[ 6,  3,  4,  8],
       [ 3,  6,  5,  1],
       [ 4,  5, 10,  7],
       [ 8,  1,  7, 25]])
array([[ 2.44948974,  0.        ,  0.        ,  0.        ],
       [ 1.22474487,  2.12132034,  0.        ,  0.        ],
       [ 1.63299316,  1.41421356,  2.30940108,  0.        ],
       [ 3.26598632, -1.41421356,  1.58771324,  3.13249102]])
array([[ 2.44948974,  1.22474487,  1.63299316,  3.26598632],
       [ 0.        ,  2.12132034,  1.41421356, -1.41421356],
       [ 0.        ,  0.        ,  2.30940108,  1.58771324],
       [ 0.        ,  0.        ,  0.        ,  3.13249102]])


- Code 8
- Consistency and Inconsistency of a system


In [1]:
# consistency and inconsistency of a system
import numpy as np
A = np.array([[10,1,1],[1,10,1],[1,1,10]])# vector
A1 = np.array( [[12,12,12]]).T
Abig=np.column_stack((A, A1)) # concatenating A & A1
print(Abig)
c=np.linalg.matrix_rank(Abig)
print(c)
d=np.linalg.matrix_rank(A)
print(d)
if (c == d):
 print('The system is consistent')
 c=np.linalg.solve(A,A1)
 print(c)
else:
 print("The system is inconsistent")

[[10  1  1 12]
 [ 1 10  1 12]
 [ 1  1 10 12]]
3
3
The system is consistent
[[1.]
 [1.]
 [1.]]
